import type { NextPage } from "next";
import { useRouter } from "next/dist/client/router";
import Head from "next/head";
import { removeTokens } from "./components/AuthLayout";
import Navbar from "./user/Home/Navbar";

const Home: NextPage = () => {
	const router = useRouter();

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			
			<Navbar />
			<button
				onClick={() => {
					removeTokens();
					router.push("/user/signin");
				}}
				className='px-3 py-2 bg-blue-500 rounded-md hover:bg-blue-600 focus:bg-blue-700'
			>
				Logout
			</button>
		</>
	);
};

export default Home;
